language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: SyxR9B4gYLsUOMn/cstJxVOQT2MIJQOmjNZlO3JlbM3zS4tUY85oUDOpkOq4KU1ZQB9qlhvlnX7DzcthSufXAmzUHzQJ4PdgaydrShetglRL1tTKTKalTMgkdRcAQ3RYrVTTDP7gYvuUSNla8Q2UACiwdyXvugAqgfuEMvMOColPvTWBb9wr/tJSdGPDYDSffaYJ243URPaAA8M8+zjP62xgeQYnAGEMqgHvjEC+AHk7UihWTyOx1zTehCZNrw2c6OfchoPbfqlt9ABtPM27BIPMe4PO1wUGj4lJ9wl0I1XnKBTkhaWO4cezp1rv75VagJZO0m+VWBkBaayxUXSbXYxpScGoQOm6fYPRtfhSC0TPSDauvoXnEbNIW3U+fw+hcVSuXJPwJ7CD+ylTOWn5Hv2mhXFQcApTPzMkycHQJI3kpfpJ3NjloUfZ1TnlU6Pcz1XYphfoDM5FHOyMnM/B75NWd4ybclJi6MACB61U9E+dzDaUePatAcPLG76YMOeFj7F9p5sEjPfm2Etjn5X2F/67/UrGkCPsTYuGNztp9fdMl0m0MtevToQhF1LPfXcwMXsAcUKqgajtS+arXxyx68jgmSAhYoDyK6IW0WKyKAcjJ0Ndr9uLLpAj1AVKcZDpGhea4xssr6cRy93M0/AmwINGfA3kjKPLT7X0isYsyHo=
  app: lit-temple-39398
  on:
    repo: hzba000/trick-server
